# Title: SRL DCF ZTP agent
# Author: Nokia
# Date: 2025-10-03
# location /etc/opt/srlinux/appmgr/configurationless.yml
configurationless:
   path: /etc/opt/srlinux/appmgr/
   launch-command: "/etc/opt/srlinux/appmgr/dcf-ztp/configurationless.sh --log-level debug"
   search-command: /bin/bash /etc/opt/srlinux/appmgr/dcf-ztp/configurationless.sh
   wait-for-config: No
   #start-order: 150
   failure-threshold: 100   # default
   failure-action: wait=5
   restricted-operations: ['quit']
   author: 'Nokia'
   run-as-user: root
   # YANG module references
   yang-modules:
       names: 
           - "configurationless"
           - "srl_nokia-common"
           - "ietf-inet-types"
           - "srl_basic_agent"
       source-directories:
           - "/etc/opt/srlinux/appmgr/dcf-ztp/yang"
           - "/opt/srlinux/models/iana"
           - "/opt/srlinux/models/ietf"
           - "/opt/srlinux/models/srl_nokia/models"



